import type { FeedEntry } from '../types'

// Mock data representing posts from a Discord music channel.
// YouTube IDs marked with a comment are well-known; others are placeholders
// to replace once a real backend is wired up.
const mockEntries: FeedEntry[] = [
  {
    id: 1,
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    genre: 'Classic Rock',
    datePosted: '2024-01-03T18:42:00',
    postedBy: 'vinyl_collector',
    youtubeId: 'fJ9rUzIMcZQ',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
    reactions: [
      { emoji: '🔥', count: 14 },
      { emoji: '👑', count: 9 },
      { emoji: '🎸', count: 6 },
    ],
  },
  {
    id: 2,
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    genre: 'Grunge',
    datePosted: '2024-01-05T21:10:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'hTWKbfoikeg',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=hTWKbfoikeg',
    reactions: [
      { emoji: '🔥', count: 11 },
      { emoji: '🤯', count: 4 },
    ],
  },
  {
    id: 3,
    title: 'Mr. Brightside',
    artist: 'The Killers',
    album: 'Hot Fuss',
    genre: 'Indie Rock',
    datePosted: '2024-01-07T15:30:00',
    postedBy: 'indie_underground',
    youtubeId: 'gGdGFtwCNBE',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=gGdGFtwCNBE',
    reactions: [
      { emoji: '❤️', count: 13 },
      { emoji: '🔥', count: 7 },
      { emoji: '😭', count: 5 },
    ],
  },
  {
    id: 4,
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    genre: 'Synth-Pop',
    datePosted: '2024-01-09T12:00:00',
    postedBy: 'synthwave_fan',
    youtubeId: '4NRXx6U8ABQ',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
    reactions: [
      { emoji: '🔥', count: 19 },
      { emoji: '💯', count: 8 },
    ],
  },
  {
    id: 5,
    title: 'Rolling in the Deep',
    artist: 'Adele',
    album: '21',
    genre: 'Pop/Soul',
    datePosted: '2024-01-11T09:15:00',
    postedBy: 'beat_curator',
    youtubeId: 'rYEDA3JcQqw',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=rYEDA3JcQqw',
    reactions: [
      { emoji: '😭', count: 10 },
      { emoji: '❤️', count: 9 },
      { emoji: '🔥', count: 6 },
    ],
  },
  {
    id: 6,
    title: 'Shake It Off',
    artist: 'Taylor Swift',
    album: '1989',
    genre: 'Pop',
    datePosted: '2024-01-13T17:55:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'nfWlot6h_JM',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=nfWlot6h_JM',
    reactions: [
      { emoji: '🎵', count: 7 },
      { emoji: '💃', count: 5 },
    ],
  },
  {
    id: 7,
    title: 'Uptown Funk',
    artist: 'Mark Ronson ft. Bruno Mars',
    album: 'Uptown Special',
    genre: 'Funk/Pop',
    datePosted: '2024-01-15T20:20:00',
    postedBy: 'bass_drop_king',
    youtubeId: 'OPf0YbXqDm0',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
    reactions: [
      { emoji: '🔥', count: 12 },
      { emoji: '💃', count: 8 },
      { emoji: '💯', count: 6 },
    ],
  },
  {
    id: 8,
    title: 'Despacito',
    artist: 'Luis Fonsi ft. Daddy Yankee',
    album: 'Vida',
    genre: 'Reggaeton',
    datePosted: '2024-01-17T14:40:00',
    postedBy: 'beat_curator',
    youtubeId: 'kJQP7kiw5Fk',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    reactions: [
      { emoji: '🔥', count: 16 },
      { emoji: '🎵', count: 4 },
    ],
  },
  {
    id: 9,
    title: 'Lose Yourself',
    artist: 'Eminem',
    album: '8 Mile (Soundtrack)',
    genre: 'Hip-Hop',
    datePosted: '2024-01-19T22:00:00',
    postedBy: 'bass_drop_king',
    youtubeId: '_Yhyp-_hX2s',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=_Yhyp-_hX2s',
    reactions: [
      { emoji: '🔥', count: 18 },
      { emoji: '💯', count: 11 },
      { emoji: '🤯', count: 7 },
    ],
  },
  {
    id: 10,
    title: 'Happy',
    artist: 'Pharrell Williams',
    album: 'G I R L',
    genre: 'Neo Soul',
    datePosted: '2024-01-21T10:30:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'ZbZSe6N_BXs',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=ZbZSe6N_BXs',
    reactions: [
      { emoji: '😊', count: 9 },
      { emoji: '🎵', count: 5 },
    ],
  },
  {
    id: 11,
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    genre: 'Pop',
    datePosted: '2024-01-23T16:45:00',
    postedBy: 'vinyl_collector',
    youtubeId: 'JGwWNGJdvx8',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    reactions: [
      { emoji: '❤️', count: 8 },
      { emoji: '🔥', count: 6 },
    ],
  },
  {
    id: 12,
    title: 'Somebody That I Used to Know',
    artist: 'Gotye ft. Kimbra',
    album: 'Making Mirrors',
    genre: 'Indie Pop',
    datePosted: '2024-01-25T19:10:00',
    postedBy: 'indie_underground',
    youtubeId: '8UVNT4wvIGY',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=8UVNT4wvIGY',
    reactions: [
      { emoji: '😭', count: 13 },
      { emoji: '❤️', count: 7 },
    ],
  },
  {
    id: 13,
    title: 'Get Lucky',
    artist: 'Daft Punk ft. Pharrell Williams',
    album: 'Random Access Memories',
    genre: 'Electronic',
    datePosted: '2024-01-27T21:30:00',
    postedBy: 'synthwave_fan',
    youtubeId: '5NV6Rdv1h3Q',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=5NV6Rdv1h3Q',
    reactions: [
      { emoji: '🕺', count: 11 },
      { emoji: '🔥', count: 8 },
      { emoji: '💯', count: 5 },
    ],
  },
  {
    id: 14,
    title: 'HUMBLE.',
    artist: 'Kendrick Lamar',
    album: 'DAMN.',
    genre: 'Hip-Hop',
    datePosted: '2024-01-29T18:00:00',
    postedBy: 'bass_drop_king',
    youtubeId: 'tvtjnkiqSZk',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=tvtjnkiqSZk',
    reactions: [
      { emoji: '🔥', count: 20 },
      { emoji: '👑', count: 12 },
      { emoji: '💯', count: 9 },
    ],
  },
  {
    id: 15,
    title: "God's Plan",
    artist: 'Drake',
    album: 'Scorpion',
    genre: 'Hip-Hop',
    datePosted: '2024-01-31T14:20:00',
    postedBy: 'beat_curator',
    youtubeId: 'xpVfcZ0ZcFM',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=xpVfcZ0ZcFM',
    reactions: [
      { emoji: '🔥', count: 9 },
      { emoji: '💯', count: 5 },
    ],
  },
  {
    id: 16,
    title: 'Do I Wanna Know?',
    artist: 'Arctic Monkeys',
    album: 'AM',
    genre: 'Indie Rock',
    datePosted: '2024-02-02T20:45:00',
    postedBy: 'indie_underground',
    youtubeId: 'bpOSxM0UIJ4',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=bpOSxM0UIJ4',
    reactions: [
      { emoji: '❤️', count: 16 },
      { emoji: '🎸', count: 10 },
      { emoji: '🔥', count: 8 },
    ],
  },
  {
    id: 17,
    title: 'One More Time',
    artist: 'Daft Punk',
    album: 'Discovery',
    genre: 'Electronic',
    datePosted: '2024-02-04T23:00:00',
    postedBy: 'synthwave_fan',
    youtubeId: 'FGBhQbmPwH8',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=FGBhQbmPwH8',
    reactions: [
      { emoji: '🕺', count: 14 },
      { emoji: '🔥', count: 10 },
    ],
  },
  {
    id: 18,
    title: 'Master of Puppets',
    artist: 'Metallica',
    album: 'Master of Puppets',
    genre: 'Heavy Metal',
    datePosted: '2024-02-06T17:15:00',
    postedBy: 'metal_mayhem',
    youtubeId: 'E0ozmU9cJDg',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=E0ozmU9cJDg',
    reactions: [
      { emoji: '🤘', count: 18 },
      { emoji: '🔥', count: 12 },
      { emoji: '💀', count: 7 },
    ],
  },
  {
    id: 19,
    title: 'Enter Sandman',
    artist: 'Metallica',
    album: 'Metallica (Black Album)',
    genre: 'Heavy Metal',
    datePosted: '2024-02-08T21:30:00',
    postedBy: 'metal_mayhem',
    youtubeId: 'CD-E-LDc384',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=CD-E-LDc384',
    reactions: [
      { emoji: '🤘', count: 15 },
      { emoji: '💀', count: 9 },
    ],
  },
  {
    id: 20,
    title: 'Redbone',
    artist: 'Childish Gambino',
    album: '"Awaken, My Love!"',
    genre: 'Funk/Soul',
    datePosted: '2024-02-10T13:00:00',
    postedBy: 'beat_curator',
    youtubeId: 'Kp7eSUU9oy8',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=Kp7eSUU9oy8',
    reactions: [
      { emoji: '🔥', count: 17 },
      { emoji: '😭', count: 8 },
      { emoji: '❤️', count: 11 },
    ],
  },
  {
    id: 21,
    title: 'The Less I Know the Better',
    artist: 'Tame Impala',
    album: 'Currents',
    genre: 'Psychedelic Pop',
    datePosted: '2024-02-12T19:45:00',
    postedBy: 'indie_underground',
    youtubeId: '2SUwOgmvzK4',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=2SUwOgmvzK4',
    reactions: [
      { emoji: '🌀', count: 13 },
      { emoji: '❤️', count: 9 },
      { emoji: '🔥', count: 6 },
    ],
  },
  {
    id: 22,
    title: 'Back in Black',
    artist: 'AC/DC',
    album: 'Back in Black',
    genre: 'Classic Rock',
    datePosted: '2024-02-14T22:10:00',
    postedBy: 'vinyl_collector',
    youtubeId: 'pAgnJDJN4VA',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=pAgnJDJN4VA',
    reactions: [
      { emoji: '🎸', count: 10 },
      { emoji: '🔥', count: 8 },
    ],
  },
  {
    id: 23,
    title: 'Shallow',
    artist: 'Lady Gaga & Bradley Cooper',
    album: 'A Star Is Born (Soundtrack)',
    genre: 'Pop/Country',
    datePosted: '2024-02-16T15:30:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'bo_efYLyVdc',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=bo_efYLyVdc',
    reactions: [
      { emoji: '😭', count: 15 },
      { emoji: '❤️', count: 12 },
    ],
  },
  {
    id: 24,
    title: 'Alright',
    artist: 'Kendrick Lamar',
    album: 'To Pimp a Butterfly',
    genre: 'Hip-Hop',
    datePosted: '2024-02-18T18:00:00',
    postedBy: 'bass_drop_king',
    youtubeId: 'Z-48u_uWMHY',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=Z-48u_uWMHY',
    reactions: [
      { emoji: '✊', count: 11 },
      { emoji: '🔥', count: 9 },
      { emoji: '💯', count: 7 },
    ],
  },
  {
    id: 25,
    title: 'Purple Rain',
    artist: 'Prince',
    album: 'Purple Rain',
    genre: 'R&B/Rock',
    datePosted: '2024-02-20T21:15:00',
    postedBy: 'vinyl_collector',
    youtubeId: 'TvnYmWpD_T8',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=TvnYmWpD_T8',
    reactions: [
      { emoji: '👑', count: 14 },
      { emoji: '😭', count: 9 },
      { emoji: '❤️', count: 8 },
    ],
  },
  {
    id: 26,
    title: 'Take Five',
    artist: 'Dave Brubeck Quartet',
    album: 'Time Out',
    genre: 'Jazz',
    datePosted: '2024-02-22T14:00:00',
    postedBy: 'jazz_aficionado',
    youtubeId: 'vmDDOFXSgAs',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=vmDDOFXSgAs',
    reactions: [
      { emoji: '🎷', count: 12 },
      { emoji: '🎹', count: 7 },
      { emoji: '👏', count: 5 },
    ],
  },
  {
    id: 27,
    title: 'So What',
    artist: 'Miles Davis',
    album: 'Kind of Blue',
    genre: 'Jazz',
    datePosted: '2024-02-24T11:30:00',
    postedBy: 'jazz_aficionado',
    youtubeId: 'ylXk1LBvIqU',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=ylXk1LBvIqU',
    reactions: [
      { emoji: '🎷', count: 10 },
      { emoji: '🤯', count: 6 },
    ],
  },
  {
    id: 28,
    title: 'Superstition',
    artist: 'Stevie Wonder',
    album: 'Talking Book',
    genre: 'R&B/Soul',
    datePosted: '2024-02-26T16:45:00',
    postedBy: 'beat_curator',
    youtubeId: '0CFuCYNx-1g',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=0CFuCYNx-1g',
    reactions: [
      { emoji: '🔥', count: 13 },
      { emoji: '🎹', count: 9 },
      { emoji: '💯', count: 6 },
    ],
  },
  {
    id: 29,
    title: 'Seven Nation Army',
    artist: 'The White Stripes',
    album: 'Elephant',
    genre: 'Blues Rock',
    datePosted: '2024-02-28T20:00:00',
    postedBy: 'vinyl_collector',
    youtubeId: '0J2QdDbelmY',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=0J2QdDbelmY',
    reactions: [
      { emoji: '🎸', count: 11 },
      { emoji: '🔥', count: 7 },
    ],
  },
  {
    id: 30,
    title: 'Creep',
    artist: 'Radiohead',
    album: 'Pablo Honey',
    genre: 'Alternative Rock',
    datePosted: '2024-03-01T22:30:00',
    postedBy: 'indie_underground',
    youtubeId: 'XFkzRNyygfk',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=XFkzRNyygfk',
    reactions: [
      { emoji: '😭', count: 16 },
      { emoji: '❤️', count: 10 },
      { emoji: '🎸', count: 5 },
    ],
  },
  // ── page 2 ────────────────────────────────────────────────────────────────
  {
    id: 31,
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: 'Appetite for Destruction',
    genre: 'Classic Rock',
    datePosted: '2024-03-03T19:00:00',
    postedBy: 'metal_mayhem',
    youtubeId: '1w7OgIMMRc4',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=1w7OgIMMRc4',
    reactions: [
      { emoji: '🎸', count: 14 },
      { emoji: '🔥', count: 10 },
    ],
  },
  {
    id: 32,
    title: 'Old Town Road',
    artist: 'Lil Nas X',
    album: '7 EP',
    genre: 'Country Rap',
    datePosted: '2024-03-05T14:10:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'r7qovpFAGrQ',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=r7qovpFAGrQ',
    reactions: [
      { emoji: '🤠', count: 8 },
      { emoji: '🔥', count: 6 },
    ],
  },
  {
    id: 33,
    title: 'Dog Days Are Over',
    artist: 'Florence + The Machine',
    album: 'Lungs',
    genre: 'Indie Pop',
    datePosted: '2024-03-07T17:30:00',
    postedBy: 'indie_underground',
    youtubeId: 'KkGVmN68ByU',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=KkGVmN68ByU',
    reactions: [
      { emoji: '🌸', count: 11 },
      { emoji: '❤️', count: 8 },
    ],
  },
  {
    id: 34,
    title: 'Sandstorm',
    artist: 'Darude',
    album: 'Before the Storm',
    genre: 'Electronic',
    datePosted: '2024-03-09T23:59:00',
    postedBy: 'synthwave_fan',
    youtubeId: 'y6120QOlsfU',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=y6120QOlsfU',
    reactions: [
      { emoji: '🏜️', count: 22 },
      { emoji: '🔥', count: 15 },
      { emoji: '💯', count: 10 },
    ],
  },
  {
    id: 35,
    title: 'Under the Bridge',
    artist: 'Red Hot Chili Peppers',
    album: 'Blood Sugar Sex Magik',
    genre: 'Alternative Rock',
    datePosted: '2024-03-11T16:20:00',
    postedBy: 'vinyl_collector',
    youtubeId: 'glen72LD4bGA',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=glen72LD4bGA',
    reactions: [
      { emoji: '❤️', count: 12 },
      { emoji: '😭', count: 6 },
    ],
  },
  {
    id: 36,
    title: 'Sicko Mode',
    artist: 'Travis Scott',
    album: 'Astroworld',
    genre: 'Hip-Hop',
    datePosted: '2024-03-13T21:00:00',
    postedBy: 'bass_drop_king',
    youtubeId: '6ONRf7h3Mdk',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=6ONRf7h3Mdk',
    reactions: [
      { emoji: '🔥', count: 9 },
      { emoji: '🤯', count: 5 },
    ],
  },
  {
    id: 37,
    title: 'Piano Man',
    artist: 'Billy Joel',
    album: 'Piano Man',
    genre: 'Classic Rock',
    datePosted: '2024-03-15T19:30:00',
    postedBy: 'jazz_aficionado',
    youtubeId: 'gxEPV4kolz0',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=gxEPV4kolz0',
    reactions: [
      { emoji: '🎹', count: 13 },
      { emoji: '❤️', count: 9 },
      { emoji: '🍺', count: 7 },
    ],
  },
  {
    id: 38,
    title: 'Levels',
    artist: 'Avicii',
    album: 'True',
    genre: 'Electronic',
    datePosted: '2024-03-17T00:30:00',
    postedBy: 'synthwave_fan',
    youtubeId: '_ovdm2yX4MA',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=_ovdm2yX4MA',
    reactions: [
      { emoji: '🎉', count: 11 },
      { emoji: '🔥', count: 8 },
    ],
  },
  {
    id: 39,
    title: 'Someone Like You',
    artist: 'Adele',
    album: '21',
    genre: 'Pop/Soul',
    datePosted: '2024-03-19T15:00:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'hLQl3WQQoQ0',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=hLQl3WQQoQ0',
    reactions: [
      { emoji: '😭', count: 19 },
      { emoji: '❤️', count: 14 },
    ],
  },
  {
    id: 40,
    title: 'Hotline Bling',
    artist: 'Drake',
    album: 'Views',
    genre: 'Hip-Hop',
    datePosted: '2024-03-21T18:45:00',
    postedBy: 'beat_curator',
    youtubeId: 'uxpDa-c-4Mc',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=uxpDa-c-4Mc',
    reactions: [
      { emoji: '📞', count: 10 },
      { emoji: '💃', count: 7 },
    ],
  },
  {
    id: 41,
    title: 'Come As You Are',
    artist: 'Nirvana',
    album: 'Nevermind',
    genre: 'Grunge',
    datePosted: '2024-03-23T22:00:00',
    postedBy: 'indie_underground',
    youtubeId: 'vabnZ9-ex7o',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=vabnZ9-ex7o',
    reactions: [
      { emoji: '🎸', count: 9 },
      { emoji: '❤️', count: 6 },
    ],
  },
  {
    id: 42,
    title: "I Will Always Love You",
    artist: 'Whitney Houston',
    album: 'The Bodyguard (Soundtrack)',
    genre: 'R&B/Soul',
    datePosted: '2024-03-25T20:15:00',
    postedBy: 'melodic_vibes',
    youtubeId: 'gv-UKiDHOO0',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=gv-UKiDHOO0',
    reactions: [
      { emoji: '😭', count: 17 },
      { emoji: '❤️', count: 13 },
      { emoji: '👑', count: 9 },
    ],
  },
  {
    id: 43,
    title: 'Blue (Da Ba Dee)',
    artist: 'Eiffel 65',
    album: 'Europop',
    genre: 'Electronic',
    datePosted: '2024-03-27T14:00:00',
    postedBy: 'synthwave_fan',
    youtubeId: 'zA52uNzx7Y4',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=zA52uNzx7Y4',
    reactions: [
      { emoji: '🔵', count: 14 },
      { emoji: '😂', count: 10 },
    ],
  },
  {
    id: 44,
    title: 'Roar',
    artist: 'Katy Perry',
    album: 'Prism',
    genre: 'Pop',
    datePosted: '2024-03-29T11:20:00',
    postedBy: 'beat_curator',
    youtubeId: 'CevxZvSJLk8',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=CevxZvSJLk8',
    reactions: [
      { emoji: '🦁', count: 7 },
      { emoji: '🔥', count: 4 },
    ],
  },
  {
    id: 45,
    title: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    genre: 'Classic Rock',
    datePosted: '2024-03-31T23:00:00',
    postedBy: 'vinyl_collector',
    youtubeId: 'BciS5krYL80',
    sourceType: 'youtube',
    sourceUrl: 'https://www.youtube.com/watch?v=BciS5krYL80',
    reactions: [
      { emoji: '🎸', count: 13 },
      { emoji: '🔥', count: 9 },
      { emoji: '👑', count: 6 },
    ],
  },
]

export async function fetchFeed(): Promise<FeedEntry[]> {
  // Replace this with a real API call once the backend is ready,
  // e.g.: return fetch('/api/feed').then(r => r.json())
  await new Promise<void>((resolve) => setTimeout(resolve, 150))
  return mockEntries
}
